version: '3.8'
services:
  backend:
    container_name: backend
    build: ./tir
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - app.env
    networks:
      - docker-network
  frontend:
    container_name: frontend
    build:
      context: ./ProjectReact
      args:
        - REACT_APP_API_URL=http://localhost:8080
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - docker-network
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    env_file:
      - postgres.env
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge